/**
 * @file audioManifest.ts
 * @description Audio configuration manifest mapping zones, terrains, weather, and sound effects to assets and BPMs.
 */

// --- Types Section ---
export interface AmbientConfig {
    url: string;
    volume: number;
}

export interface ZoneConfig {
    url: string | string[];
    volume?: number;
}

export interface SoundConfig {
    path: string;
    defaultVolume?: number;
    defaultPitch?: number;
}

// --- Manifest Section ---
export const AUDIO_MANIFEST = {
    ambient: {
        terrains: {
            'FOREST': { url: '/assets/Sounds/TerrainSounds/forest.mp3', volume: 0.25 },
            'FIELD': { url: '/assets/Sounds/TerrainSounds/dayfield.wav', volume: 0.25 },
            'HILLS': { url: '/assets/Sounds/TerrainSounds/mountains.wav', volume: 0.25 },
            'MOUNTAINS': { url: '/assets/Sounds/TerrainSounds/mountains.wav', volume: 0.25 },
            'MOUNTAIN': { url: '/assets/Sounds/TerrainSounds/mountains.wav', volume: 0.25 },
            'TUNNEL': { url: '/assets/Sounds/TerrainSounds/cave_tunnel.mp3', volume: 0.25 },
            'CAVE': { url: '/assets/Sounds/TerrainSounds/cave_tunnel.mp3', volume: 0.25 },
            'RAPIDS': { url: '/assets/Sounds/TerrainSounds/rapids.wav', volume: 0.25 },
            'UNDERWATER': { url: '/assets/Sounds/TerrainSounds/underwater.mp3', volume: 0.25 },

            'WATER': { url: '/assets/Sounds/TerrainSounds/shallows.wav', volume: 0.8 },
        } as Record<string, AmbientConfig>,
        weather: {
            'rain': { url: '/assets/Sounds/SoundEffects/rain.mp3', volume: 0.45 },
            'heavy-rain': { url: '/assets/Sounds/SoundEffects/rain.mp3', volume: 0.70 },
        } as Record<string, AmbientConfig>,
        zones: {
            'bree': { url: '/assets/Sounds/ZoneSounds/BreeSound.wav' },
            'bree land': { url: '/assets/Sounds/ZoneSounds/BreeSound.wav' },
            'the bree land': { url: '/assets/Sounds/ZoneSounds/BreeSound.wav' },
            'old east road': { url: ['/assets/Sounds/ZoneSounds/oldeastroad.mp3', '/assets/Sounds/ZoneSounds/oldeastroad2.mp3'] },
            'the old east road': { url: ['/assets/Sounds/ZoneSounds/oldeastroad.mp3', '/assets/Sounds/ZoneSounds/oldeastroad2.mp3'] },
            'shire': { url: '/assets/Sounds/ZoneSounds/Shire.mp3' },
            'the shire': { url: '/assets/Sounds/ZoneSounds/Shire.mp3' },
            'blue mountains': { url: '/assets/Sounds/ZoneSounds/BlueMountains.mp3' },
            'the blue mountains': { url: '/assets/Sounds/ZoneSounds/BlueMountains.mp3' },
            'old forest': { url: '/assets/Sounds/ZoneSounds/OldForest.mp3', volume: 4.0 },
            'the old forest': { url: '/assets/Sounds/ZoneSounds/OldForest.mp3', volume: 4.0 },
            'rivendell': { url: ['/assets/Sounds/ZoneSounds/Rivendell1.mp3', '/assets/Sounds/ZoneSounds/Rivendell2.mp3', '/assets/Sounds/ZoneSounds/Rivendell3.mp3'] },
            'grey havens': { url: '/assets/Sounds/ZoneSounds/GrayHavens1.mp3' },
            'the grey havens': { url: '/assets/Sounds/ZoneSounds/GrayHavens1.mp3' },
            'north anduin': { url: ['/assets/Sounds/ZoneSounds/northanduin.mp3', '/assets/Sounds/ZoneSounds/northanduin.mp3'], volume: 4.0 },
            'the northern anduin vale': { url: ['/assets/Sounds/ZoneSounds/northanduin.mp3', '/assets/Sounds/ZoneSounds/northanduin.mp3'], volume: 4.0 },
            'road to tharbad': { url: ['/assets/Sounds/ZoneSounds/roadtotharbad.mp3', '/assets/Sounds/ZoneSounds/roadtotharbad.mp3'] },
            'the road to tharbad': { url: ['/assets/Sounds/ZoneSounds/roadtotharbad.mp3', '/assets/Sounds/ZoneSounds/roadtotharbad.mp3'] },
            'road to fornost': { url: '/assets/Sounds/ZoneSounds/roadtofornost1.mp3' },
            'the road to fornost': { url: '/assets/Sounds/ZoneSounds/roadtofornost1.mp3' },
            'fornost': { url: '/assets/Sounds/ZoneSounds/Fornost.mp3' },
            "deadmen's dike": { url: '/assets/Sounds/ZoneSounds/Fornost.mp3' },
            'lhun valley': { url: '/assets/Sounds/ZoneSounds/LhunValley.mp3' },
            'ancient broken road': { url: '/assets/Sounds/ZoneSounds/AncientBrokenRoad.mp3' },
            'the ancient broken road': { url: '/assets/Sounds/ZoneSounds/AncientBrokenRoad.mp3' },
            'barrow downs': { url: '/assets/Sounds/ZoneSounds/barrowdowns2.mp3' },
            'the barrow downs': { url: '/assets/Sounds/ZoneSounds/barrowdowns2.mp3' },
            'dunland': { url: '/assets/Sounds/ZoneSounds/Dunland.mp3', volume: 4.0 },
            'dunlend': { url: '/assets/Sounds/ZoneSounds/Dunland.mp3', volume: 4.0 },
            'emyn nu fuin': { url: '/assets/Sounds/ZoneSounds/Emyn.mp3', volume: 4.0 },
            'emyn': { url: '/assets/Sounds/ZoneSounds/Emyn.mp3', volume: 4.0 },
            'eregion': { url: '/assets/Sounds/ZoneSounds/Eregion.mp3' },
            'ettenmoors': { url: '/assets/Sounds/ZoneSounds/Ettenmoors.mp3' },
            'the ettenmoors': { url: '/assets/Sounds/ZoneSounds/Ettenmoors.mp3' },
            'gladden fields': { url: '/assets/Sounds/ZoneSounds/GladdenFields.mp3', volume: 4.0 },
            'the gladden fields': { url: '/assets/Sounds/ZoneSounds/GladdenFields.mp3', volume: 4.0 },
            'goblin town': { url: '/assets/Sounds/ZoneSounds/GoblinTown.mp3', volume: 4.0 },
            'the goblin town': { url: '/assets/Sounds/ZoneSounds/GoblinTown.mp3', volume: 4.0 },
            'goblintown': { url: '/assets/Sounds/ZoneSounds/GoblinTown.mp3', volume: 4.0 },
            'the goblintown': { url: '/assets/Sounds/ZoneSounds/GoblinTown.mp3', volume: 4.0 },
            'lorien': { url: '/assets/Sounds/ZoneSounds/Lorien1.mp3' },
            'the lorien surroundings': { url: '/assets/Sounds/ZoneSounds/Lorien1.mp3' },
            'midgewaters': { url: '/assets/Sounds/ZoneSounds/MidgeWater.mp3', volume: 4.0 },
            'the midgewaters': { url: '/assets/Sounds/ZoneSounds/MidgeWater.mp3', volume: 4.0 },
            'moria': { url: '/assets/Sounds/ZoneSounds/Moria.mp3' },
            'the moria': { url: '/assets/Sounds/ZoneSounds/Moria.mp3' },
            'misty mountains': { url: ['/assets/Sounds/ZoneSounds/MistyMountains.mp3', '/assets/Sounds/ZoneSounds/MistyMountains2.mp3'], volume: 4.0 },
            'the misty mountains': { url: ['/assets/Sounds/ZoneSounds/MistyMountains.mp3', '/assets/Sounds/ZoneSounds/MistyMountains2.mp3'], volume: 4.0 },
            'ost in edhil': { url: '/assets/Sounds/ZoneSounds/Ost-in-edhil.mp3', volume: 4.0 },
            'road to grey havens': { url: '/assets/Sounds/ZoneSounds/RoadtoGreyHavens.mp3' },
            'the road to grey havens': { url: '/assets/Sounds/ZoneSounds/RoadtoGreyHavens.mp3' },
            'rohan': { url: '/assets/Sounds/ZoneSounds/Rohan.mp3' },
            'central anduin': { url: '/assets/Sounds/ZoneSounds/Central Anduin2.mp3', volume: 4.0 },
            'central anduin vale': { url: '/assets/Sounds/ZoneSounds/Central Anduin2.mp3', volume: 4.0 },
            'dol guldur': { url: '/assets/Sounds/ZoneSounds/Dolguldur.mp3' },
            'swanfleet': { url: '/assets/Sounds/ZoneSounds/MidgeWater.mp3', volume: 4.0 },
            'isengard': { url: '/assets/Sounds/ZoneSounds/Isengard.mp3' },
            'southern mirkwood': { url: '/assets/Sounds/ZoneSounds/SouthernMirkwood.mp3', volume: 4.0 },
            'old forest road': { url: '/assets/Sounds/ZoneSounds/TheOldForestRoad.mp3' },
            'tower hills': { url: '/assets/Sounds/ZoneSounds/TowerHills.mp3', volume: 4.0 },
            'redhorn': { url: '/assets/Sounds/ZoneSounds/Redhorn.mp3' },
            'redhorn pass': { url: '/assets/Sounds/ZoneSounds/Redhorn.mp3' },
            'tharbad': { url: '/assets/Sounds/ZoneSounds/Tharbad.mp3' },
            'trollshaws': { url: '/assets/Sounds/ZoneSounds/TrollShaws.mp3', volume: 4.0 },
            'the trollshaws': { url: '/assets/Sounds/ZoneSounds/TrollShaws.mp3', volume: 4.0 },
            'troll warrens': { url: '/assets/Sounds/ZoneSounds/warrens.mp3', volume: 4.0 },
            'the troll warrens': { url: '/assets/Sounds/ZoneSounds/warrens.mp3', volume: 4.0 },
            'warrens': { url: '/assets/Sounds/ZoneSounds/warrens.mp3', volume: 4.0 },
            'the warrens': { url: '/assets/Sounds/ZoneSounds/warrens.mp3', volume: 4.0 },
            'weathertop': { url: '/assets/Sounds/ZoneSounds/Weathertop.mp3', volume: 4.0 },
            'the weathertop': { url: '/assets/Sounds/ZoneSounds/Weathertop.mp3', volume: 4.0 },
            'valinor': { url: '/assets/Sounds/ZoneSounds/Valinor.mp3', volume: 4.0 },
            'the valinor': { url: '/assets/Sounds/ZoneSounds/Valinor.mp3', volume: 4.0 },
            'fangorn': { url: '/assets/Sounds/ZoneSounds/FangornForest.mp3', volume: 4.0 },
            'the fangorn': { url: '/assets/Sounds/ZoneSounds/FangornForest.mp3', volume: 4.0 },
            'account': { url: '/assets/Sounds/ZoneSounds/Lorien1.mp3' }
        } as Record<string, ZoneConfig>,
        special: {
            drumLoop: { url: '/assets/Sounds/SoundEffects/drumbeat.mp3' }
        } as Record<string, ZoneConfig>
    },
    effects: {
        'arrowhit': { path: '/assets/Sounds/SoundEffects/arrowhit.mp3' },
        'bash': { path: '/assets/Sounds/SoundEffects/bash.mp3' },
        'cleave': { path: '/assets/Sounds/SoundEffects/cleave.mp3' },
        'click': { path: '/assets/Sounds/SoundEffects/click.mp3' },
        'commsend': { path: '/assets/Sounds/UI/commsend.mp3', defaultVolume: 0.65 },
        'enter': { path: '/assets/Sounds/UI/enter.mp3', defaultVolume: 0.5 },
        'exit': { path: '/assets/Sounds/UI/exit.mp3', defaultVolume: 0.5 },
        'drawertab': { path: '/assets/Sounds/UI/drawertab.mp3', defaultVolume: 0.06 },
        'actionmenu': { path: '/assets/Sounds/UI/actionmenu.mp3', defaultVolume: 0.1 },
        'commbubble': { path: '/assets/Sounds/SoundEffects/commbubble.mp3' },
        'door1': { path: '/assets/Sounds/SoundEffects/door1.wav' },
        'hit-impact': { path: '/assets/Sounds/SoundEffects/hit-impact.mp3' },
        'hit2': { path: '/assets/Sounds/SoundEffects/hit2.mp3' },
        'incantations': { path: '/assets/Sounds/SoundEffects/incantations.mp3' },
        'kill': { path: '/assets/Sounds/UI/rip.mp3' },
        'level': { path: '/assets/Sounds/SoundEffects/level.wav' },
        'magicexplosion': { path: '/assets/Sounds/SoundEffects/magicexplosion.mp3' },
        'move': { path: '/assets/Sounds/SoundEffects/move.mp3' },
        'miss': { path: '/assets/Sounds/SoundEffects/miss.mp3' },
        'oof': { path: '/assets/Sounds/SoundEffects/oof.mp3' },
        'pierce': { path: '/assets/Sounds/SoundEffects/pierce.mp3' },
        'sellandbuy': { path: '/assets/Sounds/SoundEffects/sellandbuy.mp3' },
        'slash': { path: '/assets/Sounds/SoundEffects/slash.mp3' },
        'smite': { path: '/assets/Sounds/SoundEffects/smite.mp3' },
        'stab': { path: '/assets/Sounds/SoundEffects/stab.mp3' },
        'thunder': { path: '/assets/Sounds/SoundEffects/thunder.mp3' },
        'thunder2': { path: '/assets/Sounds/SoundEffects/thunder2.mp3' },
        'typing': { path: '/assets/Sounds/UI/typing.mp3', defaultVolume: 0.18, defaultPitch: 1.0 },
        'ambient-thunder': { path: '/assets/Sounds/SoundEffects/ambientthunder.mp3' },
        'watermove': { path: '/assets/Sounds/SoundEffects/watermove.mp3' },
        'achievement': { path: '/assets/Sounds/UI/achievement.mp3', defaultVolume: 0.9 },
        'event-move': { path: '/assets/Sounds/UI/move.mp3', defaultVolume: 0.4 },
        'wear': { path: '/assets/Sounds/UI/wear.mp3', defaultVolume: 0.8 },
        'remove': { path: '/assets/Sounds/UI/remove.mp3', defaultVolume: 0.8 },
        'loadflag': { path: '/assets/Sounds/UI/loadflag.mp3', defaultVolume: 0.3 },
        'ride': { path: '/assets/Sounds/UI/ride.mp3', defaultVolume: 0.8 },
        'stopriding': { path: '/assets/Sounds/UI/stopriding.mp3', defaultVolume: 0.8 },
        'target': { path: '/assets/Sounds/UI/target.mp3', defaultVolume: 0.07 },
        'help': { path: '/assets/Sounds/UI/help.mp3', defaultVolume: 0.8 },
    } as Record<string, SoundConfig>,
    bpmMap: {
        'AncientBrokenRoad.mp3': 72,
        'BlueMountains.mp3': 64,
        'BreeSound.wav': 96,
        'CentralAnduin.mp3': 60,
        'Central Anduin2.mp3': 60,
        'Dolguldur.mp3': 64,
        'Dunland.mp3': 112,
        'Emyn.mp3': 104,
        'Eregion.mp3': 76,
        'Ettenmoors.mp3': 72,
        'FangornForest.mp3': 88,
        'Fornost.mp3': 72,
        'GladdenFields.mp3': 64,
        'GoblinTown.mp3': 100,
        'GrayHavens1.mp3': 76,
        'Isengard.mp3': 96,
        'LhunValley.mp3': 96,
        'Lorien1.mp3': 112,
        'MidgeWater.mp3': 88,
        'MistyMountains.mp3': 96,
        'MistyMountains2.mp3': 60,
        'Moria.mp3': 92,
        'NorthAnduin.mp3': 64,
        'northanduin.mp3': 64,
        'OldForest.mp3': 88,
        'oldeastroad.mp3': 64,
        'oldeastroad2.mp3': 64,
        'Ost-in-edhil.mp3': 112,
        'Redhorn.mp3': 80,
        'Rivendell1.mp3': 60,
        'Rivendell2.mp3': 92,
        'Rivendell3.mp3': 112,
        'RoadToGreyHavens.mp3': 92,
        'RoadToTharbad.mp3': 88,
        'roadtofornost1.mp3': 96,
        'roadtotharbad.mp3': 64,
        'Rohan.mp3': 80,
        'Shire.mp3': 64,
        'SouthernMirkwood.mp3': 64,
        'Tharbad.mp3': 88,
        'TheOldForestRoad.mp3': 64,
        'TowerHills.mp3': 80,
        'TrollShaws.mp3': 64,
        'Valinor.mp3': 76,
        'warrens.mp3': 94,
        'Weathertop.mp3': 112,
        'barrowdowns2.mp3': 60,
        'drumbeat.mp3': 112,
    } as Record<string, number>
};
