import { MAGE_ATTACK_BUTTONS } from './mage_attack';
import { MAGE_UTILITY_BUTTONS } from './mage_utility';
import { MAGE_INTEL_BUTTONS } from './mage_intel';
import { CLERIC_UTILITY_BUTTONS } from './cleric_utility';
import { CLERIC_COMBAT_BUTTONS } from './cleric_combat';
import { CLERIC_BUFF_BUTTONS } from './cleric_buff';
import { CLERIC_HIGH_BUTTONS } from './cleric_high';

export { 
    MAGE_ATTACK_BUTTONS, MAGE_UTILITY_BUTTONS, MAGE_INTEL_BUTTONS,
    CLERIC_UTILITY_BUTTONS, CLERIC_COMBAT_BUTTONS, CLERIC_BUFF_BUTTONS, CLERIC_HIGH_BUTTONS 
};

// Compatibility aliases
export const MAGE_ATTACK_SPELLS = MAGE_ATTACK_BUTTONS;
export const MAGE_UTILITY_SPELLS = MAGE_UTILITY_BUTTONS;
export const MAGE_INTEL_SPELLS = MAGE_INTEL_BUTTONS;
export const CLERIC_UTILITY_SPELLS = CLERIC_UTILITY_BUTTONS;
export const CLERIC_COMBAT_SPELLS = CLERIC_COMBAT_BUTTONS;
export const CLERIC_BUFF_SPELLS = CLERIC_BUFF_BUTTONS;
export const CLERIC_HIGH_SPELLS = CLERIC_HIGH_BUTTONS;
