import { GameStats, DrawerLine, GameAction, PopoverState, CaptureStage, CombatHealthStatus, QuestData, GameEntity, EntityLocation } from '../../types';

export interface UseGameParserDeps {
    isInventoryOpen: boolean; isEquipmentOpen: boolean; isCharacterOpen: boolean; isStatsOpen: boolean; isPlayersOpen: boolean; mapperRef: React.RefObject<any>;
    btn: { buttonsRef: React.RefObject<any[]>; setButtons: React.Dispatch<React.SetStateAction<any[]>>; buttonTimers: React.RefObject<Record<string, ReturnType<typeof setTimeout>>>; setActiveSet: (setId: string) => void; };
    addMessage: (type: any, text: string, combatOverride?: boolean, mid?: string, isRoomName?: boolean, precalculated?: { textOnly: string, lower: string }, shopItem?: any, practiceSkill?: any, practiceHeader?: any, skipBrevity?: boolean, replyTarget?: string, replyCommand?: string, commSender?: string, commAction?: string, commText?: string, commColor?: string, combatSide?: 'player' | 'opponent' | 'groupmate') => void;
    pendingGmcpCommRef?: React.MutableRefObject<{ sender: string; chan: string; msg?: string } | null>;
    lastCommIdBySenderRef?: React.MutableRefObject<Map<string, string>>;
    playSound: (buffer: AudioBuffer) => void;
    playHitImpactSound?: () => void;
    playIncantationSound?: () => void;
    stopIncantationSound?: (andExplode: boolean) => void;
    playMagicExplosionSound?: () => void;
    playRandomSound: (buffers: AudioBuffer[]) => void;
    playDoorSound: (isOpen: boolean) => void;
    triggerHaptic: (ms: number) => void;
    setWeather: (val: any) => void; setIsFoggy: (val: boolean) => void;
    setStats: (val: GameStats | ((prev: GameStats) => GameStats)) => void;
    setAbilities: (val: Record<string, number> | ((prev: Record<string, number>) => Record<string, number>)) => void;
    setCharacterClass: (val: any) => void; setRumble: (val: boolean) => void;
    setHitFlash: (val: boolean) => void; setDeathStage: (val: any) => void;
    setInCombat: (val: boolean, force?: boolean) => void;
    inCombatRef: React.RefObject<boolean>;
    setLightningEnabled: (val: boolean) => void;
    setPlayerPosition: (val: string) => void; detectLighting: (light: string) => void;
    setCurrentTerrain?: (terrain: string) => void;
    setMood: (val: string) => void;
    setPlayerHealthStatus: (val: CombatHealthStatus | null) => void;
    setOpponentHealthStatus: (val: CombatHealthStatus | null) => void;
    registerEntity: (id: string, name: string, location: EntityLocation, category?: string) => GameEntity;
    setOpponentName: (val: string | null) => void;
    setBufferHealthStatus: (val: CombatHealthStatus | null) => void;
    setBufferName: (val: string | null) => void;
    isSoundEnabledRef: React.RefObject<boolean>; soundTriggersRef: React.RefObject<any[]>;
    actionsRef: React.RefObject<GameAction[]>;
    executeCommandRef: React.RefObject<(cmd: string, silent?: boolean, isSystem?: boolean, isHistorical?: boolean, fromDrawer?: boolean) => void>;
    setCharacterInfo: (val: import('../../types').CharacterInfo | ((prev: import('../../types').CharacterInfo) => import('../../types').CharacterInfo)) => void;
    characterInfo: import('../../types').CharacterInfo;
    setInventoryLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setStatsLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setEqLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setEntities: React.Dispatch<React.SetStateAction<Record<string, GameEntity>>>;
    setWhoList: React.Dispatch<React.SetStateAction<string[]>>;
    setWhereList: React.Dispatch<React.SetStateAction<import('../../types').WhereEntry[]>>;
    captureStage: React.MutableRefObject<CaptureStage>;
    practice: any;
    isDrawerCapture: React.MutableRefObject<number>;
    isSilentCapture: React.MutableRefObject<number>;
    isWaitingForStats: React.MutableRefObject<boolean>;
    isWaitingForEq: React.MutableRefObject<boolean>;
    isWaitingForInv: React.MutableRefObject<boolean>;
    keywordOverrides: Record<string, string>;
    roomNameRef: React.RefObject<string | null>;
    roomName: string | null;
    showDebugEchoes?: boolean;
    addDiagnosticLog?: (msg: string) => void;
    popoverState: PopoverState | null;
    setPopoverState: React.Dispatch<React.SetStateAction<PopoverState | null>>;
    pendingDrawerContainerRef?: React.MutableRefObject<{ containerId: string; cmd: 'inventorylist' | 'equipmentlist'; afterId: string } | null>;
    setDiscoveredItems: React.Dispatch<React.SetStateAction<string[]>>;
    setQuests: (val: QuestData | ((prev: QuestData) => QuestData)) => void;
    quests: QuestData;
    mumeEditState: { isOpen: boolean; title: string; text: string; key: string };
    setMumeEditState: React.Dispatch<React.SetStateAction<{ isOpen: boolean; title: string; text: string; key: string }>>;
    shop: any;
    triggerXpTicker?: () => void;
    groupMembers: import('../../types').GroupMember[];
    deathRoomId: string | null;
    setDeathRoomId: (val: string | null) => void;
    accountState: import('../../types').AccountState;
    setAccountState: React.Dispatch<React.SetStateAction<import('../../types').AccountState>>;
    setGameState: React.Dispatch<React.SetStateAction<import('../../types').GameState>>;
    activePrompt: string;
    gameState: import('../../types').GameState;
    isMobile?: boolean;
}
