import { GameStats, DrawerLine, GameAction, PopoverState, CaptureStage, CombatHealthStatus, QuestData, GameEntity, EntityLocation } from '../../types';

export interface UseGameParserDeps {
    entities: Record<string, GameEntity>;
    isInventoryOpen: boolean; isEquipmentOpen: boolean; isCharacterOpen: boolean; isStatsOpen: boolean; isPlayersOpen: boolean; mapperRef: React.RefObject<any>;
    btn: { buttonsRef: React.RefObject<any[]>; setButtons: React.Dispatch<React.SetStateAction<any[]>>; buttonTimers: React.RefObject<Record<string, ReturnType<typeof setTimeout>>>; setActiveSet: (setId: string) => void; };
    addMessage: (type: any, text: string, combatOverride?: boolean, mid?: string, isRoomName?: boolean, precalculated?: { textOnly: string, lower: string }, shopItem?: any, practiceSkill?: any, practiceHeader?: any, skipBrevity?: boolean, replyTarget?: string, replyCommand?: string, commSender?: string, commAction?: string, commText?: string, commColor?: string, combatSide?: 'player' | 'opponent' | 'groupmate', providedIsHitImpact?: boolean) => void;
    addSystemMessage: (text: string) => void;
    pendingGmcpCommRef?: React.MutableRefObject<{ sender: string; chan: string; msg?: string } | null>;
    lastCommIdBySenderRef?: React.MutableRefObject<Map<string, string>>;
    playSound: (buffer: AudioBuffer) => void;
    playHitImpactSound?: (options?: { pitch?: number, volume?: number }) => void;
    playOofSound?: (options?: { pitch?: number, volume?: number }) => void;
    playSlashSound?: (options?: { pitch?: number, volume?: number }) => void;
    playCleaveSound?: (options?: { pitch?: number, volume?: number }) => void;
    playSmiteSound?: (options?: { pitch?: number, volume?: number }) => void;
    playPierceSound?: (options?: { pitch?: number, volume?: number }) => void;
    playStabSound?: (options?: { pitch?: number, volume?: number }) => void;
    playCommMessageSound?: (options?: { volume?: number }) => void;
    playBuySellSound?: (options?: { volume?: number }) => void;
    playBashSound?: (options?: { pitch?: number, volume?: number }) => void;
    loadBashSound?: () => void;
    playIncantationSound?: () => void;
    stopIncantationSound?: (andExplode: boolean) => void;
    playMagicExplosionSound?: () => void;
    playRandomSound: (buffers: AudioBuffer[]) => void;
    playDoorSound: (isOpen: boolean) => void;
    playMovementSound?: (isRiding?: boolean) => void;
    triggerHaptic: (ms: number) => void;
    setPlayerPosition: (val: string) => void; 
    setCurrentTerrain?: (terrain: string) => void;
    setMood: (val: string) => void;
    setPlayerHealthStatus: (val: CombatHealthStatus | null) => void;
    setOpponentHealthStatus: (val: CombatHealthStatus | null) => void;
    registerEntity: (id: string, name: string, location: EntityLocation, category?: string) => GameEntity;
    setOpponentName: (val: string | null) => void;
    setBufferHealthStatus: (val: CombatHealthStatus | null) => void;
    setBufferName: (val: string | null) => void;
    isSoundEnabledRef: React.RefObject<boolean>; soundTriggersRef: React.RefObject<any[]>;
    actionsRef: React.RefObject<GameAction[]>;
    executeCommandRef: React.RefObject<(cmd: string, silent?: boolean, isSystem?: boolean, isHistorical?: boolean, fromDrawer?: boolean) => void>;
    setCharacterInfo: (val: import('../../types').CharacterInfo | ((prev: import('../../types').CharacterInfo) => import('../../types').CharacterInfo)) => void;
    characterInfo: import('../../types').CharacterInfo;
    setInventoryLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setStatsLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setInfoLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setScoreLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setQuestLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setPracticeLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setWhoLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setWhereLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setEqLines: React.Dispatch<React.SetStateAction<DrawerLine[]>>;
    setEntities: React.Dispatch<React.SetStateAction<Record<string, GameEntity>>>;
    setWhoList: React.Dispatch<React.SetStateAction<string[]>>;
    setWhereList: React.Dispatch<React.SetStateAction<import('../../types').WhereEntry[]>>;
    captureStage: React.MutableRefObject<CaptureStage>;
    practice: any;
    isDrawerCapture: React.MutableRefObject<number>;
    isSilentCapture: React.MutableRefObject<number>;
    isWaitingForStats: React.MutableRefObject<boolean>;
    isWaitingForEq: React.MutableRefObject<boolean>;
    isWaitingForInv: React.MutableRefObject<boolean>;
    isWaitingForInfo: React.MutableRefObject<boolean>;
    keywordOverrides: Record<string, string>;
    roomNameRef: React.RefObject<string | null>;
    roomDescRef?: React.RefObject<string>;
    roomName: string | null;
    showDebugEchoes?: boolean;
    addDiagnosticLog?: (msg: string) => void;
    popoverState: PopoverState | null;
    setPopoverState: React.Dispatch<React.SetStateAction<PopoverState | null>>;
    pendingDrawerContainerRef?: React.MutableRefObject<{ containerId: string; cmd: 'inventorylist' | 'equipmentlist'; afterId: string } | null>;
    setDiscoveredItems: React.Dispatch<React.SetStateAction<string[]>>;
    setQuests: (val: QuestData | ((prev: QuestData) => QuestData)) => void;
    quests: QuestData;
    mumeEditState: { isOpen: boolean; title: string; text: string; key: string };
    setMumeEditState: React.Dispatch<React.SetStateAction<{ isOpen: boolean; title: string; text: string; key: string }>>;
    shop: any;
    triggerXpTicker?: () => void;
    triggerHitFlash?: () => void;
    triggerOppHitFlash?: () => void;
    groupMembers: import('../../types').GroupMember[];
    deathRoomId: string | null;
    setDeathRoomId: (val: string | null) => void;
    accountState: import('../../types').AccountState;
    setAccountState: React.Dispatch<React.SetStateAction<import('../../types').AccountState>>;
    accountStageRef: React.MutableRefObject<import('../../types').AccountStage>;
    setGameState: React.Dispatch<React.SetStateAction<import('../../types').GameState>>;
    activePrompt: string;
    gameState: import('../../types').GameState;
    isMobile?: boolean;
    playerPosition?: string;
    isSpectateMode?: boolean;
    spectateTarget?: import('../../types').GroupMember | null;
    setSpectateStats: (stats: GameStats | ((prev: GameStats) => GameStats)) => void;
    setSpectateHealthStatus: (status: CombatHealthStatus | null) => void;
    setSpectateOpponentName: (name: string | null) => void;
    setSpectateOpponentStatus: (status: CombatHealthStatus | null) => void;
    setSpectatePosition: (pos: string) => void;
    setSpectateWaiting: (val: boolean) => void;
    setSpectateRoomName: (name: string | null) => void;
    setSpectateTerrain: (terrain: string) => void;
    setSpectateRoomZone: (zone: string | null) => void;
    setSpectateLighting: (light: import('../../types').LightingType) => void;
    setSpectateWeather: (w: import('../../types').WeatherType) => void;
    setSpectateIsFoggy: (f: boolean) => void;
    setSpectateInCombat: (val: boolean) => void;
    setSpectateCharacterName: (name: string | null) => void;
    setSpectateGroupMembers: React.Dispatch<React.SetStateAction<import('../../types').GroupMember[]>>;
    spectateStats: GameStats;
    spectateRoomDesc?: string | null;
    setSpectateRoomDesc?: (desc: string | null) => void;
    characterName: string | null;
    setRoomPlayers: React.Dispatch<React.SetStateAction<import('../../types').GmcpOccupant[]>>;
    setRoomNpcs: React.Dispatch<React.SetStateAction<import('../../types').GmcpOccupant[]>>;
    detectLighting?: (light: number | string) => void;
    setWeather?: (w: import('../../types').WeatherType) => void;
    setIsFoggy?: (f: boolean) => void;
    setStats: (val: GameStats | ((prev: GameStats) => GameStats)) => void;
    setRoomItems: React.Dispatch<React.SetStateAction<import('../../types').GmcpOccupant[]>>;
    setRoomName: (name: string | null) => void;
    setRoomDesc: (desc: string | null) => void;
    setRoomExits: (exits: string[]) => void;
    setAbilities: (val: Record<string, number> | ((prev: Record<string, number>) => Record<string, number>)) => void;
    setCharacterClass: (val: any) => void;
    setInCombat: (val: boolean, force?: boolean) => void;
    inCombatRef: React.RefObject<boolean>;
    setLightningEnabled: (val: boolean) => void;
    setMessages: React.Dispatch<React.SetStateAction<import('../../types').Message[]>>;
    clearLog: () => void;
    isNewbieMode: boolean;
    processMessageHtml?: (originalHtml: string, mid: string, isRoomName: boolean, type?: import('../../types').MessageType, isCombatMessage?: boolean, combatSide?: 'player' | 'opponent' | 'groupmate') => string;
    spectateCharacterName: string | null;
    roomPlayers: import('../../types').GmcpOccupant[];
    sessionMode?: 'live' | 'replay';
    help: any;
    setIsPasswordMode: (val: boolean) => void;
    spectateQueue: string[];
    setSpectateQueue: (val: string[] | ((prev: string[]) => string[])) => void;
    lastSnoopStartTime: number | null;
    setLastSnoopStartTime: (val: number | null) => void;
    setIsSpectateMode: (val: boolean) => void;
}
